defaults:
  - _self_

data:
  raw_path: "data/raw/fma_large"
  processed_path: "data/processed/fma_arrow"
  sample_rate: 32000
  num_classes: 8          # Quan trọng: Hardcode số lượng Genre để Model Output Layer dùng

audio:
  n_mels: 128
  n_fft: 1024
  hop_length: 320         # BẮT BUỘC: 32000 * 3 / 320 = 300 frames
  duration: 3             # seconds
  segment_overlap: 1.5    # 50% overlap cho Data Augmentation

training:
  batch_size: ???
  epochs: ???
  learning_rate: ???
  seed: 2026
